#ifndef DEFINICOES_H
#define DEFINICOES_H

#define CARACTER_MASCARA_SENHA '*'
#define CARACTER_SEPARACAO ','
#define CARACTER_FINAL_DE_LINHA "\n"

#define TAMANHO_MAXIMO_CARACTERES_LINHA 1000
#define TAMANHO_MAXIMO_CARACTERES_USUARIO 100
#define TAMANHO_MAXIMO_CARACTERES_NOME 100
#define TAMANHO_MAXIMO_CARACTERES_DESCRICAO 200

#define CAMIMNHO_ARQUIVO_USUARIO "db\\Usuarios.txt"
#define CAMIMNHO_ARQUIVO_PORCAO_ALIMENTO "db\\PorcaoAlimento.txt"

#endif /* DEFINICOES_H */
